### ISSUE TITLE
关于源码

### ISSUE THREAD

**Issue by zengyazy** [yizhen20133868/Retriever-Dialogue#1]
您好，我对这篇论文很感兴趣，想根据更多实现细节来学习，请问可以公开源码吗。

**Comment by qinlibo-hit** [comment]
@zengyazy 感谢关注我们的工作，但是之前没有整理，代码较难找到，有任何问题，可以发送邮件lbqin@ir.hit.edu.cn,或者可以了解我们最新的ACL2020工作代码 https://github.com/LooperXX/DF-Net
